version: 1.0
name: contract_deploy
stages:
  template-init:
    steps:
      - name: set workdir
        uses: workdir
        with:
          workdir: $HOME/my-erc20

  contract-compile:
    needs:
      - template-init
    steps:
      - name: deploy
        run: |
          npm install -g truffle
          truffle compile

  contract-upload:
    needs:
      - contract-compile
    steps:
      - name: upload
        action: hamster/ipfs
        with:
          path: xxx
