---
apiVersion: v1
kind: Service
metadata:
  name: hamster-aline-master
spec:
  selector:
    app: hamster-aline-master
  type: NodePort
  ports:
    - name: aline-master-web
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30302
    - name: aline-master-grpc
      protocol: TCP
      port: 50001
      targetPort: 50001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hamster-aline-master
  labels:
    app: hamster-aline-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hamster-aline-master
  template:
    metadata:
      labels:
        app: hamster-aline-master
    spec:
      containers:
        - name: hamster-aline-master
          image: hamstershare/hamster-develop:${PIPELINE_ID}
          imagePullPolicy: Always
          env:
            - name: DB_HOST
              value: mysql
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: hamster-aline
                  key: db_password
            - name: DOCKER_HOST
              value: tcp://docker:2376
            - name: DOCKER_CERT_PATH
              value: /certs/client
            - name: DOCKER_TLS_VERIFY
              value: "1"
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /root/pipelines
              name: aline-pipelines
            - mountPath: /root/workdir
              name: aline-workdir
            - mountPath: /certs
              name: docker-tls
              readOnly: true
            - name: kubeconfig
              mountPath: "/root/.kube"
              readOnly: true
      volumes:
        - name: aline-pipelines
          persistentVolumeClaim:
            claimName: aline-pipelines
        - name: aline-workdir
          persistentVolumeClaim:
            claimName: aline-workdir
        - name: docker-tls
          persistentVolumeClaim:
            claimName: docker-tls
        - name: kubeconfig
          configMap:
            # Provide the name of the ConfigMap you want to mount.
            name: kubeconfig
            # An array of keys from the ConfigMap to create as files
            items:
              - key: "kubeconfig"
                path: "config"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hamster-aline-worker-1
  labels:
    app: hamster-aline-worker-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hamster-aline-worker-1
  template:
    metadata:
      labels:
        app: hamster-aline-worker-1
    spec:
      containers:
        - name: hamster-aline-worker-1
          image: hamstershare/hamster-develop-worker:${PIPELINE_ID}
          imagePullPolicy: Always
          env:
            - name: MASTER_ADDRESS
              value: hamster-aline:50001
            - name: DOCKER_HOST
              value: tcp://docker:2376
            - name: DOCKER_CERT_PATH
              value: /certs/client
            - name: DOCKER_TLS_VERIFY
              value: "1"
          volumeMounts:
            - mountPath: /certs
              name: docker-tls
              readOnly: true
      volumes:
        - name: docker-tls
          persistentVolumeClaim:
            claimName: docker-tls
---
apiVersion: v1
kind: Service
metadata:
  name: docker
spec:
  selector:
    app: docker
  type: ClusterIP
  ports:
    - name: docker-rpc
      protocol: TCP
      port: 2376
      targetPort: 2376
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker
  labels:
    app: docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
        - name: docker
          image: docker:dind
          imagePullPolicy: IfNotPresent
          args:
            - --storage-driver
            - overlay2
          env:
            - name: DOCKER_TLS_CERTDIR
              value: /certs
          ports:
            - containerPort: 2376
          volumeMounts:
            - mountPath: /root/pipelines
              name: aline-pipelines
            - mountPath: /root/workdir
              name: aline-workdir
            - mountPath: /certs
              name: docker-tls
          securityContext:
            privileged: true
      volumes:
        - name: aline-pipelines
          persistentVolumeClaim:
            claimName: aline-pipelines
        - name: aline-workdir
          persistentVolumeClaim:
            claimName: aline-workdir
        - name: docker-tls
          persistentVolumeClaim:
            claimName: docker-tls
