version: "1"
name: pipeline
stages:
  init:
    steps:
      - name: set workdir
        uses: workdir
        with:
          workdir: /Users/mohaijiang/IdeaProjects/blockchain/a-line
  build:
    steps:
      - name: build
        run: |
          make linux-test
          docker buildx build -t hamstershare/hamster-develop:${PIPELINE_ID} --platform=linux/amd64 --push .
          docker buildx build -f Dockerfile_worker -t hamstershare/hamster-develop-worker:${PIPELINE_ID} --platform=linux/amd64 --push .

  deploy:
    needs:
      - init
    steps:
      - name: deploy
        run: |
          envsubst < grpc-deploy.yml | kubectl -n hamster apply -f -

