version: 1.0
name:  [[ .Name ]]
stages:
  Initialization:
    steps:
      - name: Clone Code from Github
        uses: git-checkout
        with:
          url: [[ .RepositoryUrl ]]
          branch: ${{ param.branch }}
  Build Contract:
    needs:
      - Initialization
    steps:
      - name: install dependency
        runs-on: node:18
        run: |
          npm install
      - name: Compile Contract
        runs-on: ghcr.io/foundry-rs/foundry:latest
        run: |
          forge install
          forge build
      - name: Filter Info
        run: |
          mkdir -p build/artifacts
          cd out
          find . -type f -name '*.json' | while read -r i; do
              bytecode=$(jq -r '.bytecode .object' "$i")
              length=$(jq '.abi | length' "$i")

              if [ "$bytecode" = "0x" ] || [ "$length" -eq 0 ]; then
                  echo "$i"
              else
                  my_string=$(jq -r '.metadata .sources | keys | join(" ")' "$i")
                  all_start_with_node_modules=true

                  for element in $my_string; do
                      if [ ! "$(echo "$element" | grep '^node_modules')" ]; then
                          echo "element" "$element"
                          all_start_with_node_modules=false
                          break
                      fi
                  done
                  if $all_start_with_node_modules; then
                      echo "no ok: $i"
                  else
                      echo "ok: $i"
                      cp -R "$i" ../build/artifacts/
                  fi
              fi
          done;
  Output Results:
    needs:
      - Build Contract
    steps:
      - name: Save Files
        uses: hamster-artifactory
        with:
          name: contract-meta.zip
          compress: false
          path: |
            build/artifacts/*.json
