version: "1"
name: [[.Name]]
stages:
  Deploy FrontEnd by K8s:
    steps:
      - name: deploy
        uses: k8s-frontend-deploy
        with:
          namespace: ${{ param.namespace }}
          containers: ${{ param.containers }}
          project_name: ${{ param.projectName }}
          service_ports: ${{ param.servicePorts }}
  Assigning Domains:
    needs:
      - Deploy FrontEnd by K8s
    steps:
      - name: assign-domain
        uses: k8s-assign-domain
        with:
          gateway: ${{ param.gateway }}
          namespace: ${{ param.namespace }}
          project_name: ${{ param.projectName }}
          service_ports: ${{ param.servicePorts }}