version: 1.0
name: [[.Name]]
stages:
  Deploy FrontEnd :
    steps:
      - name: Upload to IPFS
        uses: hamster-ipfs
        with:
          api: http://44.204.204.186:5001
          arti_url: ${{ param.ArtifactUrl }}
          gateway: http://g.alpha.hamsternet.io
          base_dir: ${{ param.baseDir }}
