version: "1"
name: {{.Name}}
stages:
  init:
    steps:
      - name: git clone
        uses: git-checkout
        with:
          url: {{ .RepositoryUrl }}
          branch: main
  build:
    needs:
      - init
    steps:
      - name: build
        run: |
          npm install
          npm run build:staging 
          docker buildx build -t {{ .Image }} --platform=linux/amd64 .
          docker push {{ .Image }}

  deploy:
    steps:
      - name: deploy
        uses: k8s-frontend-deploy
        with:
          gateway: http://61.172.179.6
          namespace: ${{ param.Namespace }}
          containers: ${{ param.Containers }}
          project_name: ${{ param.ProjectName }}
          service_ports: ${{ param.ServicePorts }}


