version: "1"
name: [[.Name]]
stages:
  k8s-deploy:
    steps:
      - name: deploy
        uses: k8s-frontend-deploy
        with:
          gateway: http://61.172.179.6
          namespace: ${{ param.namespace }}
          containers: ${{ param.containers }}
          project_name: ${{ param.projectName }}
          service_ports: ${{ param.servicePorts }}
          image: ${{ param.image }}
