version: 1.0
name: [[.Name]]
stages:
  ipfs :
    steps:
      - name: artifactory
        uses: hamster-ipfs
        with:
          api: http://34.232.105.81:5001
          arti_url: ${{ param.ArtifactUrl }}
          gateway: http://g.develop.hamsternet.io
          base_dir: ${{ param.baseDir }}
