version: 1.0
name: [[ .Name ]]
stages:
  Initialization:
    steps:
      - name: Clone Code from Github
        uses: git-checkout
        with:
          url: [[ .RepositoryUrl ]]
          branch: ${{ param.branch }}
  Build FrontEnd:
    needs:
      - Initialization
    steps:
      - name: Compile Code
        run: |
          npm install
          npm run build
      - name: Build Image
        uses: image-build
        with:
          image_name: ${{ param.imageName }}
  Output Results:
    needs:
      - Build FrontEnd
    steps:
      - name: Save Image
        uses: image-push
        with:
          image_name: ${{ param.imageName }}

