version: 1.0
name: [[ .Name ]]
stages:
  Initialization:
    steps:
      - name: Clone Code from Github
        uses: git-checkout
        with:
          url: [[ .RepositoryUrl ]]
          branch: ${{ param.branch }}
  Build FrontEnd:
    needs:
      - Initialization
    steps:
      - name: Compile Code
        run: |
          npm install
          npm run build
      - name: Compile Code
        uses: icp-build
        with:
          dfx_json: ${{ param.dfxJson }}
  Output Results:
    needs:
      - Build
    steps:
      - name: Save Package
        uses: hamster-artifactory
        with:
          name: icp-build.zip
          path: |
            dfx.json
            canister_ids.json
            .dfx
            dist
