version: 1.0
name: [[ .Name ]]
stages:
  Initialization:
    steps:
      - name: Clone Code from Github
        uses: git-checkout
        with:
          url: [[ .RepositoryUrl ]]
          branch: main
  Build FrontEnd:
    needs:
      - Initialization
    steps:
      - name: Compile Code
        run: |
          npm install
          npm run build
  Output Results:
    needs:
      - Build FrontEnd
    steps:
      - name: Save Package
        uses: hamster-artifactory
        with:
          name: frontend.zip
          path: |
            dist
