version: 1.0
name: [[ .Name ]]
stages:
  Initialization:
    steps:
      - name: Clone Code from Github
        uses: git-checkout
        with:
          url: [[ .RepositoryUrl ]]
          branch: ${{ param.branch }}

  Build Contract:
    needs:
      - Initialization
    steps:
      - name: Compile Contract
        runs-on: jlvihv/cairo-anaconda-env:0.1.4
        run: |
          cd cairo-project
          for f in *.cairo; do
            echo "Compiling $f..."
            starknet-compile $f > $f.starknet.output.json
          done
  Output Results:
    needs:
      - Build Contract
    steps:
      - name: Save Files
        uses: hamster-artifactory
        with:
          name: some.zip
          compress: false
          path: |
            /cairo-project/*.output.json
