version: 1.0
name: {{.Name}}
stages:
  Initialization:
    steps:
      - name: Clone Code from Github
        uses: git-checkout
        with:
          url: {{ .RepositoryUrl }}
          branch: main
      - name: Run Install
        run: |
            npm install

#  Check by Sol-Profile...:
#    needs:
#      - Initialization
#    steps:
#      - name: sol-profiler-install
#        run: |
#          npm install --global sol-profiler
#          npm install
#      - name: sol-profiler-check
#        uses: sol-profiler-check
#        with:
#          path: contracts
  Check Contract:
    needs:
      - Initialization
    steps:
      - name: Install Solhint
        run: |
          npm install -g solhint
      - name: Check by Solhint
        uses: solhint-check
        with:
          path: contracts
      - name: Check by Mythril
        uses: mythril-check
        with:
          path: contracts
          solc-version: 0.8.9
      - name: Start Local Chain
        run: |
          npm install -g ganache
          if [ -f "command.pid" ]; then
            kill -9 `cat command.pid`  || (echo 'No such process ')
          fi
          nohup ganache > ganache.log 2>&1& echo $! > command.pid
          sleep 2
      - name: Check by eth-gas-report
        uses: eth-gas-reporter
        with:
          solc-version:
      - name: Check by AI
        uses: openai
  Output Results:
    needs:
      - Check Contract
    steps:
      - name: Integration Report
        uses: check-aggregation

