version: 1.0
name: {{.Name}}
stages:
  Initialization:
    steps:
      - name: git-clone
        uses: git-checkout
        with:
          url: {{ .RepositoryUrl }}
          branch: main
      - name: npm install
        run: |
            npm install

#  Check by Sol-Profile...:
#    needs:
#      - Initialization
#    steps:
#      - name: sol-profiler-install
#        run: |
#          npm install --global sol-profiler
#          npm install
#      - name: sol-profiler-check
#        uses: sol-profiler-check
#        with:
#          path: contracts

  Check by Solhint:
    needs:
      - Initialization
    steps:
      - name: solhint-install
        run: |
          npm install -g solhint
      - name: solhint-check
        uses: solhint-check
        with:
          path: contracts

  Check by Mythril:
    needs:
      - Check by Solhint
    steps:
      - name: mythril-check
        uses: mythril-check
        with:
          path: contracts
          solc-version: 0.8.9

  Check by eth-gas-reporter:
    needs:
      - Check by Mythril
    steps:
      - name: gas-install
        run: |
          npm install
      - name: start-local-chain
        run: |
          npm install -g ganache
          if [ -f "command.pid" ]; then
            kill -9 `cat command.pid`  || (echo 'No such process ')
          fi
          nohup ganache > ganache.log 2>&1& echo $! > command.pid
          sleep 2
      - name: eth-gas-reporter
        uses: eth-gas-reporter
        with:
          solc-version:

  Check by AI:
    needs:
      - Check by eth-gas-reporter
    steps:
      - name: openai ask
        uses: openai


  Output Results:
    needs:
      - Check by AI
    steps:
      - name: check-aggregation
        uses: check-aggregation

