version: 1.0
name: {{.Name}}
stages:
  Initialization:
    steps:
      - name: git-clone
        uses: git-checkout
        with:
          url: {{ .RepositoryUrl }}
          branch: main

  Check by Sol-Profile...:
    needs:
      - git-clone
    steps:
      - name: sol-profiler-install
        run: |
          npm install --global sol-profiler
      - name: sol-profiler-check
        uses: sol-profiler-check
        with:
          path: contracts

  Check by Solhint:
    needs:
      - sol-profiler-check
    steps:
      - name: sol-profiler-install
        run: |
          npm install -g solhint
      - name: solhint-check
        uses: solhint-check
        with:
          path: contracts

  Check by Mythril:
    needs:
      - solhint-check
    steps:
      - name: mythril-check
        uses: mythril-check
        with:
          path: contracts
          solc-version: 0.6.0

  Output Results:
    needs:
      - solhint-check
    steps:
      - name: check-aggregation
        uses: check-aggregation
