version: 1.0
name: {{.Name}}
stages:
  git-clone:
    steps:
      - name: git-clone
        uses: git-checkout
        with:
          url: {{ .RepositoryUrl }}
          branch: main

  sol-profiler-check:
    needs:
      - git-clone
    steps:
      - name: sol-profiler-install
        run: |
          npm install --global sol-profiler
      - name: sol-profiler-check
        uses: sol-profiler-check
        with:
          path:

  solhint-check:
    needs:
      - sol-profiler-check
    steps:
      - name: sol-profiler-install
        run: |
          npm install -g solhint
      - name: solhint-check
        uses: solhint-check
        with:
          path:

#  mythril-check:
#    needs:
#      - solhint-check
#    steps:
#      - name: mythril-check
#        uses: mythril-check
#        with:
#          path:
