version: 1.0
name: {{.Name}}
stages:
  Initialization:
    steps:
      - name: git-clone
        uses: git-checkout
        with:
          url: {{ .RepositoryUrl }}
          branch: main
      - name: npm install
        run: |
            npm install

#  Check by Sol-Profile...:
#    needs:
#      - Initialization
#    steps:
#      - name: sol-profiler-install
#        run: |
#          npm install --global sol-profiler
#          npm install
#      - name: sol-profiler-check
#        uses: sol-profiler-check
#        with:
#          path: contracts

  Check by Solhint:
    needs:
      - Initialization
    steps:
      - name: solhint-install
        run: |
          npm install -g solhint
      - name: solhint-check
        uses: solhint-check
        with:
          path: contracts

  Check by Mythril:
    needs:
      - Check by Solhint
    steps:
      - name: mythril-check
        uses: mythril-check
        with:
          path: contracts
          solc-version: 0.8.9

  Output Results:
    needs:
      - Check by Mythril
    steps:
      - name: check-aggregation
        uses: check-aggregation

  openai check:
    needs:
      - Output Results
    steps:
      - name: openai ask
        uses: openai
