version: 1.0
name: {{.Name}}
stages:
  git-clone:
    steps:
      - name: git-clone
        uses: git-checkout
        with:
          url: {{ .RepositoryUrl }}
          branch: main
  code-compile:
    needs:
      - git-clone
    steps:
      - name: code-compile
        run: |
          npm install -g truffle
          truffle compile

      - name: save artifactory
        uses: hamster-artifactory
        with:
          name: contract-meta.zip
          path: |
            build/contracts/*.json
