version: 1.0
name: aptos
stages:
  git-clone:
    steps:
      - name: git-clone
        uses: git-checkout
        with:
          url: https://github.com/hamster-template/aptos-token-staking.git
          branch: main
  code-compile:
    needs:
      - git-clone
    steps:
      - name: code-compile
        runs-on: docker.io/hamstershare/aptoslabs/tools:aptos-node-v1.3.0
        run: |
          aptos move compile --save-metadata --named-addresses mokshyastaking=0x0ff505af704efc4b90f0f5fd526c1d169e4852dcfe6efaf915d08b7285944e26

      - name: save artificate
        uses: hamster-artifactory
        with:
          name: aptos-meta.zip
          compress: false
          path: |
            build/*/package-metadata.bcs
            build/*/bytecode_modules/*.mv
