version: 1.0
name: frontend
stages:
  Initialization:
    steps:
      - name: git-clone
        uses: git-checkout
        with:
          url: https://github.com/abing258/frontend-Template.git
          branch: master

  code-compile:
    needs:
      - Initialization
    steps:
      - name: code-compile
        run: |
          npm install
          npm run build
      - name: save artifactory
        uses: hamster-artifactory
        with:
          name: frontend.zip
          path: |
            dist

  ipfs:
    needs:
      - code-compile
    steps:
      - name: update ipfs
        uses: hamster-ipfs
        with:
          path: dist
