version: "1.0"
name: 781e52d9-eea8-4a44-956d-44fddcd6a4e9_12537
stages:
  Deploy FrontEnd:
    steps:
      - name: Upload to IPFS
        uses: hamster-ipfs
        with:
          api: https://ipfs-console.gke.hamsternet.io
          arti_url: ${{ param.ArtifactUrl }}
          base_dir: ${{ param.baseDir }}
          gateway: ${{param.ipfsGateway}}
        volumes: []
parameter:
  ArtifactUrl: file:///tmp/frontend.zip
  baseDir: dist
  buildWorkflowDetailId: "12571"
  ipfsGateway: "https://g.alpha.hamsternet.io"
