version: 1.0
name: mythril-check
stages:
  git-clone:
    steps:
      - name: git-clone
        uses: git-checkout
        with:
          url: https://github.com/abing258/solidity_contracts.git
          branch: main
  mythril-check:
    needs:
      - git-clone
    steps:
      - name: mythril-check
        uses: mythril-check
        with:
          path:
          solc-version: 0.8.13
