version: 1.0
name: my-gear
stages:
  clone-code-gear-hello-world:
    steps:
      - name: set workdir
        uses: workdir
        with:
          workdir: $HOME/workdir/my-gear/hello-world
      - name: git clone gear hello world
        uses: git-checkout
        with:
          url: https://github.com/jlvihv/gear-hello-world
          branch: main
  clone-code-gear-deploy-script:
    steps:
      - name: set workdir
        uses: workdir
        with:
          workdir: $HOME/workdir/my-gear/gear-deploy
      - name: git clone gear deploy script
        uses: git-checkout
        with:
          url: https://github.com/jlvihv/gear-deploy
          branch: hello-world

  gear-code-compile:
    needs:
      - clone-code-gear-hello-world
    steps:
      - name: set workdir
        uses: workdir
        with:
          workdir: $HOME/workdir/my-gear/hello-world
      - name: make hello world
        run: |
          make
      - name: set workdir
        uses: workdir
        with:
          workdir: $HOME/workdir/my-gear/gear-deploy
      - name: gear deploy
        run: |
          npm install
          npm run code:submit
      - name: set workdir
        uses: workdir
        with:
          workdir: $HOME/workdir/my-gear/hello-world/frontend
      - name: make hello world frontend
        run: |
          cp .env.example .env
          cat ../../gear-deploy/programID.txt >> .env
          yarn
          yarn add @polkadot/util-crypto
          yarn run start